base_url = "https://htmx.org"
title = "</> htmx - high power tools for html"
theme = "htmx-theme"

compile_sass = false
build_search_index = false

taxonomies = [
  { name = "tag", render = false, feed = true }
]

[markdown]
highlight_code = true
highlight_theme = "visual-studio-dark"
external_links_target_blank = true
smart_punctuation = true

[slugify]
paths_keep_dates = true

[extra]
# Put all your custom variables here
